---
#Install all nesessary software
- name: Make sure we can connect
  ping:
- name: Update freshly installed system
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
- name: Install MySQL and prerequisites
  apt:
    pkg:
    - python3 
    - mysql-server
    - mysql-client
    - python3-pip
    - python-setuptools
- name: install Setuptools for PyMySQL
  pip:
    name: setuptools
    state: present
- name: install PyMYSQL 
  pip:
    name: pymysql
    state: present
- include_tasks: mysql_secure_installation.yml