---
- name: Generate new root password   
  command: openssl rand -hex 7  creates=/root/.my.cnf  
  register: mysql_new_root_pass
- name: Create my_cnf    
  template: 
    src: my.cnf 
    dest: /root/.my.cnf 
  when: mysql_new_root_pass.changed
- name: Output new root password
  debug: msg={{mysql_new_root_pass.stdout}}
- name: Update root password
  shell: mysql -u root -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_new_root_pass.stdout}}"; FLUSH PRIVILEGES;'
  when: mysql_new_root_pass.changed
- name: Remove anonymous users
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock 
    name: "" 
    state: absent 
  when: mysql_new_root_pass.changed
- name: Remove test database   
  mysql_db: 
    name: test 
    state: absent 
  when: mysql_new_root_pass.changed  